POST http://localhost:3000/v3/mail/send
Authorization: Bearer sendgrid-api-key
Content-Type: application/json

{
    "personalizations": [
        {
            "to": [{
                "email": "to@example.com"
            }, {
                "email": "to2@example.com"
            }]
        }
    ],
    "from": {
        "email": "from@example.com"
    },
    "subject": "important subject",
    "content": [
        {
            "type": "text/plain",
            "value": "even more important content"
        }
    ]
}
